/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  publishedAt: string;
  isArchived?: boolean;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: CategoryReference;
  author: AuthorReference;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Table)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | CategoryReference
  | AuthorReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | Author
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../nextjs/lib/blog.ts
// Variable: latestPostsQuery
// Query: *[  _type == "post" && defined(slug.current) && defined(publishedAt) &&  publishedAt <= now() && isArchived != true] | order(publishedAt desc)[0...3] {  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,  category->{_id, title, "slug": slug.current, description},  author->{name, role, bio, avatar}}
export type LatestPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
  author: {
    name: string;
    role: string | null;
    bio: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
}>;

// Source: ../../nextjs/lib/blog.ts
// Variable: allPostsQuery
// Query: *[  _type == "post" && defined(slug.current) && defined(publishedAt) &&  publishedAt <= now() && isArchived != true] | order(publishedAt desc)[0...200] {  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,  category->{_id, title, "slug": slug.current, description},  author->{name, role, bio, avatar}}
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
  author: {
    name: string;
    role: string | null;
    bio: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
}>;

// Source: ../../nextjs/lib/blog.ts
// Variable: postBySlugQuery
// Query: *[  _type == "post" && defined(slug.current) && defined(publishedAt) &&  publishedAt <= now() && isArchived != true && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  _updatedAt,  coverImage,  category->{    _id,    title,    "slug": slug.current,    description  },  author->{    name,    role,    bio,    avatar  },  body,  seo{    metaTitle,    metaDescription,    ogImage  }}
export type PostBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
  author: {
    name: string;
    role: string | null;
    bio: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
  body: Array<
    | ({
        _key: string;
      } & Table)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: ../../nextjs/lib/blog.ts
// Variable: postSlugsQuery
// Query: *[  _type == "post" && defined(slug.current) && defined(publishedAt) &&  publishedAt <= now() && isArchived != true].slug.current
export type PostSlugsQueryResult = Array<string>;

// Source: ../../nextjs/lib/blog.ts
// Variable: relatedPostsQuery
// Query: *[  _type == "post" && defined(slug.current) && defined(publishedAt) &&  publishedAt <= now() && isArchived != true &&  _id != $currentId && category._ref == $categoryId] | order(publishedAt desc)[0...3] {  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,  category->{_id, title, "slug": slug.current, description},  author->{name, role, bio, avatar}}
export type RelatedPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
  author: {
    name: string;
    role: string | null;
    bio: string | null;
    avatar: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
}>;

// Source: ../../nextjs/lib/blog.ts
// Variable: prevNextQuery
// Query: {  "prev": *[    _type == "post" && defined(slug.current) && defined(publishedAt) &&    publishedAt <= now() && isArchived != true && publishedAt < $publishedAt  ] | order(publishedAt desc)[0] {    title,    "slug": slug.current  },  "next": *[    _type == "post" && defined(slug.current) && defined(publishedAt) &&    publishedAt <= now() && isArchived != true && publishedAt > $publishedAt  ] | order(publishedAt asc)[0] {    title,    "slug": slug.current  }}
export type PrevNextQueryResult = {
  prev: {
    title: string;
    slug: string;
  } | null;
  next: {
    title: string;
    slug: string;
  } | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "post" && defined(slug.current) && defined(publishedAt) &&\n  publishedAt <= now() && isArchived != true\n] | order(publishedAt desc)[0...3] {\n  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,\n  category->{_id, title, "slug": slug.current, description},\n  author->{name, role, bio, avatar}\n}': LatestPostsQueryResult;
    '*[\n  _type == "post" && defined(slug.current) && defined(publishedAt) &&\n  publishedAt <= now() && isArchived != true\n] | order(publishedAt desc)[0...200] {\n  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,\n  category->{_id, title, "slug": slug.current, description},\n  author->{name, role, bio, avatar}\n}': AllPostsQueryResult;
    '*[\n  _type == "post" && defined(slug.current) && defined(publishedAt) &&\n  publishedAt <= now() && isArchived != true && slug.current == $slug\n][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  _updatedAt,\n  coverImage,\n  category->{\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  },\n  author->{\n    name,\n    role,\n    bio,\n    avatar\n  },\n  body,\n  seo{\n    metaTitle,\n    metaDescription,\n    ogImage\n  }\n}': PostBySlugQueryResult;
    '*[\n  _type == "post" && defined(slug.current) && defined(publishedAt) &&\n  publishedAt <= now() && isArchived != true\n].slug.current': PostSlugsQueryResult;
    '*[\n  _type == "post" && defined(slug.current) && defined(publishedAt) &&\n  publishedAt <= now() && isArchived != true &&\n  _id != $currentId && category._ref == $categoryId\n] | order(publishedAt desc)[0...3] {\n  _id, title, "slug": slug.current, excerpt, publishedAt, _updatedAt, coverImage,\n  category->{_id, title, "slug": slug.current, description},\n  author->{name, role, bio, avatar}\n}': RelatedPostsQueryResult;
    '{\n  "prev": *[\n    _type == "post" && defined(slug.current) && defined(publishedAt) &&\n    publishedAt <= now() && isArchived != true && publishedAt < $publishedAt\n  ] | order(publishedAt desc)[0] {\n    title,\n    "slug": slug.current\n  },\n  "next": *[\n    _type == "post" && defined(slug.current) && defined(publishedAt) &&\n    publishedAt <= now() && isArchived != true && publishedAt > $publishedAt\n  ] | order(publishedAt asc)[0] {\n    title,\n    "slug": slug.current\n  }\n}': PrevNextQueryResult;
  }
}
