import assert from 'node:assert/strict';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { neon } from '@neondatabase/serverless';
process.loadEnvFile('.env.outreach.local');
if (process.env.OUTREACH_DATABASE_TEST_ALLOWED !== 'true') throw new Error('isolated_database_required');
const db = neon(process.env.OUTREACH_DATABASE_URL);
const base = process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:3101';
const origin = process.env.OUTREACH_SITE_ORIGIN || 'https://www.realismthrift.com';
const email = `http-${randomUUID()}@example.invalid`;
const [{ id }] = await db`select outreach_import_contact(${email}, 'isolated HTTP verification') as id`;
await db`select outreach_review_contact(${id}::uuid, 'unreachable isolated verification fixture')`;
const [{ message }] = await db`select outreach_prepare_message(${id}::uuid) as message`;
await db`select outreach_attach_draft(${message.outreach_id}::uuid, ${`fixture_${randomUUID()}`})`;
const token = message.unsubscribe_token;
async function contact() { return (await db`select marketing_status,preference_version from outreach_contacts where id=${id}::uuid`)[0]; }
const endpoint = `${base}/api/email-preferences/one-click?token=${token}`;
const before = await contact();
const get = await fetch(endpoint, { redirect: 'manual' });
assert.equal(get.status, 303);
assert.deepEqual(await contact(), before);
const post = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'List-Unsubscribe=One-Click', redirect: 'manual' });
assert.equal(post.status, 204);
assert.equal(post.headers.get('location'), null);
const after = await contact();
assert.equal(after.marketing_status, 'unsubscribed');
const [{ status }] = await db`select status from outreach_messages where id=${message.outreach_id}::uuid`;
assert.equal(status, 'cancelled');
const form = new FormData(); form.set('List-Unsubscribe', 'One-Click');
assert.equal((await fetch(endpoint, { method: 'POST', body: form })).status, 204);
assert.deepEqual(await contact(), after);
const confirmation = randomBytes(32).toString('base64url');
const hash = createHash('sha256').update(confirmation).digest('hex');
await db`select outreach_request_resubscribe(${email}, ${randomUUID()}, ${randomUUID()}, ${hash})`;
async function action(name) {
  const response = await fetch(`${base}/api/email-preferences`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify({ action: name, token: confirmation }) });
  assert.equal(response.status, 200);
  assert.match(response.headers.get('cache-control'), /no-store/);
  return response.json();
}
assert.equal((await action('preview_confirmation')).status, 'ready');
assert.deepEqual(await contact(), after);
assert.equal((await action('confirm_resubscribe')).status, 'confirmed');
assert.equal((await action('confirm_resubscribe')).status, 'already_confirmed');
assert.equal((await contact()).marketing_status, 'eligible');
assert.equal((await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'List-Unsubscribe=One-Click' })).status, 204);
assert.equal((await action('confirm_resubscribe')).status, 'changed');
assert.equal((await contact()).marketing_status, 'unsubscribed');
const mcp = await fetch(`${base}/api/mcp`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(mcp.status, 401);
assert.match(mcp.headers.get('www-authenticate'), /oauth-protected-resource/);
console.log('Live HTTP + isolated Neon verified: scanner GET, URL-encoded/multipart one-click, idempotence, draft cancellation, read-only preview, explicit confirmation, newer unsubscribe, MCP 401. No email sent.');
